Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# Modify organizations
Organizations:
  - &Orderer
    Name: ordererMSP
    ID: ordererMSP
    MSPDir: crypto-config/ordererOrganizations/orderer.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ordererMSP.member')"

  - &co
    Name: coMSP
    ID: coMSP
    MSPDir: crypto-config/peerOrganizations/co.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('coMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('coMSP.admin', 'coMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('coMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('coMSP.peer')"
    AnchorPeers:
      - Host: peer0.co.com # define dns / ip address if using multihost technique
        Port: 7051 # define port

  - &sl
    Name: slMSP
    ID: slMSP
    MSPDir: crypto-config/peerOrganizations/sl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('slMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('slMSP.admin', 'slMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('slMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('slMSP.peer')"
    AnchorPeers:
      - Host: peer0.sl.com
        Port: 7051

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft # define consensus type, either solo or etcdraft
  Addresses:
    - orderer.main.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities
  EtcdRaft: # if using solo consensus, remove this field
    Consenters:
      - Host: orderer.main.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/orderer.com/orderers/main.orderer.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/orderer.com/orderers/main.orderer.com/tls/server.crt
      - Host: orderer.co.com
        Port: 7055
        ClientTLSCert: crypto-config/ordererOrganizations/orderer.com/orderers/co.orderer.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/orderer.com/orderers/co.orderer.com/tls/server.crt
      - Host: orderer.sl.com
        Port: 7055
        ClientTLSCert: crypto-config/ordererOrganizations/orderer.com/orderers/sl.orderer.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/orderer.com/orderers/sl.orderer.com/tls/server.crt

Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Orderer
    Consortiums:
      TestConsortium: # rename based on Consortium name on ChannelProfile
        Organizations:
          - *co
          - *sl

  ChannelProfile:
    <<: *ChannelDefaults
    Consortium: TestConsortium # Rename Consortium name based on env file.
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *co
        - *sl