# Orderer Definition
# Note: if using raft consensus, define n+1 orderers.
#       if using solo consensus, just define 1 orderer (orderer.example.com)
OrdererOrgs:
  - Name: Orderer
    Domain: orderer.com
    Specs:
      - Hostname: main
        SANS:
          - orderer.main.com
          - 10.239.54.23
      - Hostname: co
        SANS:
          - orderer.co.com
          - 10.239.54.23
      - Hostname: sl
        SANS:
          - orderer.sl.com
          - 10.239.54.32

# Peer Definition
# Note: Peer name orderer starts from 0. peer0, peer1, etc.
PeerOrgs:
  - Name: co
    Domain: co.com
    EnableNodeOUs: true
    Template:
      Count: 1 # How many peer will be generated
    Users:
      Count: 1 # The number of user accounts _in addition_ to Admin
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.co.com
          - 10.239.54.23

  - Name: sl
    Domain: sl.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.sl.com
          - 10.239.54.32
